trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
- task: FortifySCA@6
  inputs:
      runBuildTranslate: true
      applicationType: 'dotnet'
      fortifyProjects: '**\*.sln'
      fortifyBuildId: 'test'
      runFortifyRulepackUpdate: true
      runFortifyClean: true
      scaVerbose: true
      scaDebug: true
      runFortifyScan: true
      fortifyScanType: 'LocalScan'
